server:
  port: 2000

eureka:
  instance:
    hostname: 127.0.0.1
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
     defaultZone: http://127.0.0.1:2000/eureka
spring:
  application:
    name: ha-eureka
